print('====== DESAFIO 05 ======')
alg = input('Digite algo: ')
print('O que foi digitado e alfanumerico? ', type(alg))
print('O que foi digitado so tem espaços? ', alg.isspace())
print('O que foi digitado e um numero? ', alg.isnumeric())
print('O que foi digitado e alfabetico? ', alg.isalpha())
print('O que foi digitado e alfanumerico? ', alg.isalnum())
print('O que foi digitado esta apenas em maiusculas? ', alg.isupper())
print('O que foi digitado esta apenas em minusculas? ', alg.islower())
print('O que foi digitado esta capitalizado? ', alg.istitle())

