print('====== DESAFIO 04 ======')
alg = input('Digite algo: ')
print('O que foi digitado é alfanumerico? {}'.format(type(alg)))
print('O que foi digitado so tem espaços? {}'.format(alg.isspace()))
print('O que foi digitado é um numero? {}'.format(alg.isnumeric()))
print('O que foi digitado é alfabetico? {}'.format(alg.isalpha()))
print('O que foi digitado é alfanumerico? {}'.format(alg.isalnum()))
print('O que foi digitado esta apenas em maiusculas? {}'.format(alg.isupper()))
print('O que foi digitado esta apenas em minusculas? {}'.format(alg.islower()))
print('O que foi digitado esta capitalizado? {}'.format(alg.istitle()))

